# Generated by Django 5.2.8 on 2025-11-19 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('harga_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('satuan', models.CharField(max_length=20)),
                ('bulk_size', models.IntegerField(blank=True, null=True)),
                ('bulk_discount_rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'barang',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_transaksi', models.DateTimeField(auto_now_add=True)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'transaksi',
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaksi.barang')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='transaksi.transaksi')),
            ],
            options={
                'db_table': 'detail_transaksi',
            },
        ),
    ]
